sudo: required
language: java

jdk:
  - openjdk8

env:
  - TERM=dumb

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wine lua5.2

before_script: 
  - cd de.peeeq.wurstscript
  - chmod +x gradlew

script:
  - ./gradlew assemble test --info
  
after_success:
  - ./gradlew jacocoTestReport coveralls
